"""tags add

Revision ID: 7039063a6d5e
Revises: ceca529096a0
Create Date: 2023-05-12 10:28:39.928860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7039063a6d5e'
down_revision = 'ceca529096a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR(length=200)), nullable=True), schema='hitsbulleye')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'tags', schema='hitsbulleye')
    # ### end Alembic commands ###
