"""question_log

Revision ID: 7418a2479d81
Revises: a90ac1b1bbf9
Create Date: 2023-05-18 14:40:35.409954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7418a2479d81'
down_revision = 'a90ac1b1bbf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_logs',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('question_id', sa.BIGINT(), nullable=True),
    sa.Column('previous_question', sa.TEXT(), nullable=True),
    sa.Column('next_question', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hitsbulleye'
    )
    op.create_index('question_logs_question_id_key_', 'question_logs', ['question_id'], unique=False, schema='hitsbulleye')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('question_logs_question_id_key_', table_name='question_logs', schema='hitsbulleye')
    op.drop_table('question_logs', schema='hitsbulleye')
    # ### end Alembic commands ###
