"""question_comment

Revision ID: 852a321bb175
Revises: 7039063a6d5e
Create Date: 2023-05-12 11:02:32.021959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '852a321bb175'
down_revision = '7039063a6d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_comment',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('question_id', sa.BIGINT(), nullable=False),
    sa.Column('is_internal', sa.BOOLEAN(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('parent_id', sa.BIGINT(), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hitsbulleye'
    )
    op.create_index('question_comment_question_id_key_', 'question_comment', ['question_id'], unique=False, schema='hitsbulleye')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('question_comment_question_id_key_', table_name='question_comment', schema='hitsbulleye')
    op.drop_table('question_comment', schema='hitsbulleye')
    # ### end Alembic commands ###
