"""master-test

Revision ID: a90ac1b1bbf9
Revises: 852a321bb175
Create Date: 2023-05-17 12:57:39.661000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a90ac1b1bbf9'
down_revision = '852a321bb175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_direction',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('domain_id', sa.SMALLINT(), nullable=True),
    sa.Column('test_type', sa.SMALLINT(), nullable=True),
    sa.Column('direction', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hitsbulleye'
    )
    op.create_table('test_explanation',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('test_type', sa.SMALLINT(), nullable=True),
    sa.Column('explanation', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hitsbulleye'
    )
    op.create_table('test_section',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), nullable=True),
    sa.Column('name_key', sa.VARCHAR(length=250), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hitsbulleye'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_section', schema='hitsbulleye')
    op.drop_table('test_explanation', schema='hitsbulleye')
    op.drop_table('test_direction', schema='hitsbulleye')
    # ### end Alembic commands ###
