"""initial

Revision ID: ceca529096a0
Revises: 
Create Date: 2023-05-05 08:58:31.325814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ceca529096a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('area_code', sa.VARCHAR(length=250), nullable=True),
    sa.Column('area_type', sa.SMALLINT(), nullable=True),
    sa.Column('name_key', sa.VARCHAR(length=250), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hitsbulleye'
    )
    op.create_index('area_name_key_', 'area', ['name_key'], unique=False, schema='hitsbulleye')
    op.create_table('area_direction',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hitsbulleye'
    )
    op.create_index('area_direction_area_id_key_', 'area_direction', ['area_id'], unique=False, schema='hitsbulleye')
    op.create_table('course',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('name_key', sa.VARCHAR(length=250), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hitsbulleye'
    )
    op.create_index('course_name_key_', 'course', ['name_key'], unique=False, schema='hitsbulleye')
    op.create_table('question',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('org_id', sa.BIGINT(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('area_ids', postgresql.ARRAY(sa.BIGINT()), nullable=True),
    sa.Column('lod', sa.SMALLINT(), nullable=True),
    sa.Column('question_style', sa.SMALLINT(), nullable=True),
    sa.Column('no_of_option', sa.SMALLINT(), nullable=True),
    sa.Column('marking_range', sa.SMALLINT(), nullable=True),
    sa.Column('typable_text_type', sa.SMALLINT(), nullable=True),
    sa.Column('direction_id', sa.BIGINT(), nullable=True),
    sa.Column('course_ids', postgresql.ARRAY(sa.BIGINT()), nullable=True),
    sa.Column('question_type', sa.SMALLINT(), nullable=True),
    sa.Column('answer_type', sa.SMALLINT(), nullable=True),
    sa.Column('editor', sa.SMALLINT(), nullable=True),
    sa.Column('answer', postgresql.ARRAY(sa.SMALLINT()), nullable=True),
    sa.Column('typable_answer', sa.VARCHAR(length=250), nullable=True),
    sa.Column('question', sa.TEXT(), nullable=True),
    sa.Column('explanation', sa.TEXT(), nullable=True),
    sa.Column('option1', sa.TEXT(), nullable=True),
    sa.Column('option2', sa.TEXT(), nullable=True),
    sa.Column('option3', sa.TEXT(), nullable=True),
    sa.Column('option4', sa.TEXT(), nullable=True),
    sa.Column('option5', sa.TEXT(), nullable=True),
    sa.Column('option6', sa.TEXT(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_push_to_es', sa.BOOLEAN(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hitsbulleye'
    )
    op.create_table('user_auth',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('role_id', sa.SMALLINT(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('login_email', postgresql.ARRAY(sa.VARCHAR(length=100)), nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('org_id', sa.BIGINT(), nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hitsbulleye'
    )
    op.create_index('user_auth_email_key_', 'user_auth', ['email'], unique=False, schema='hitsbulleye')
    op.create_index('user_auth_user_login_email_key_', 'user_auth', ['login_email'], unique=False, schema='hitsbulleye')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_auth_user_login_email_key_', table_name='user_auth', schema='hitsbulleye')
    op.drop_index('user_auth_email_key_', table_name='user_auth', schema='hitsbulleye')
    op.drop_table('user_auth', schema='hitsbulleye')
    op.drop_table('question', schema='hitsbulleye')
    op.drop_index('course_name_key_', table_name='course', schema='hitsbulleye')
    op.drop_table('course', schema='hitsbulleye')
    op.drop_index('area_direction_area_id_key_', table_name='area_direction', schema='hitsbulleye')
    op.drop_table('area_direction', schema='hitsbulleye')
    op.drop_index('area_name_key_', table_name='area', schema='hitsbulleye')
    op.drop_table('area', schema='hitsbulleye')
    # ### end Alembic commands ###
